src/grotto/api/urls.py
from django.conf import settings
from django.urls import include, path, re_path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions
from rest_framework.routers import DefaultRouter

from grotto.api import views

schema_view = get_schema_view(
    openapi.Info(
        title="Grotto API",
        default_version="v1",
        description="Idk",
    ),
    url=settings.DEFAULT_API_URL,
    public=True,
    permission_classes=(permissions.AllowAny,),
)

router = DefaultRouter()
router.register("game/rooms", views.RoomViewSet, basename="room")
router.register("game/items", views.ItemViewSet, basename="item")
router.register("game/characters", views.CharacterViewSet, basename="character")
router.register("game/npcs", views.NonPlayerCharacterViewSet, basename="npc")

urlpatterns = router.urls

urlpatterns += [
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    re_path(
        r"swagger(?P<format>\.json|\.yaml)$",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "docs/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("foundry/", include("foundry.api.urls", namespace="foundry-api")),
    path("guild/", include("guild.api.urls", namespace="guild-api")),
    path("maze/", include("maze.api.urls", namespace="maze-api")),
    path("account/", include("account.api.urls", namespace="account-api")),
    path("arena/", include("arena.api.urls", namespace="arena-api")),
    path("game/tableau/", views.TableauAPIView.as_view(), name="tableau"),
    path("game/enter/", views.EnterAPIView.as_view()),
]

src/grotto/game/urls.py
from django.urls import path

from grotto.game import views

app_name = "game"

urlpatterns = [
    path("play/", views.PlayView.as_view(), name="play"),
]

src/grotto/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path("api/v1/", include("grotto.api.urls")),
    path("accounts/", include("account.urls")),
    path("admin/", admin.site.urls),
    path("game/", include("grotto.game.urls")),
    path("guild/", include("guild.urls")),
    path("rooms/", include("maze.urls")),
    path(
        "",
        TemplateView.as_view(template_name="static_pages/index.html"),
        name="index",
    ),
    path("tmp", TemplateView.as_view(template_name="static_pages/tmp.html")),
    path(
        "privacy/",
        TemplateView.as_view(template_name="static_pages/privacy.html"),
        name="privacy",
    ),
    path(
        "agreement/",
        TemplateView.as_view(template_name="static_pages/agreement.html"),
        name="agreement",
    ),
    path(
        "reporting/",
        TemplateView.as_view(template_name="static_pages/reporting.html"),
        name="reporting",
    ),
]

src/maze/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from maze import views

app_name = "maze"
urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path(
        "character-map/",
        TemplateView.as_view(template_name="magicmap.html"),
        name="map",
    ),
    path("<slug:color_slug>/", views.RoomDetailView.as_view(), name="room"),
    path("cenotaph/<slug:color_slug>/", views.CenotaphView.as_view(), name="cenotaph"),
    path("graphics/<int:pk>/", views.RoomGraphicsView.as_view(), name="graphics"),
    path("cenotaph/<int:pk>/relic/", views.CenotaphRelicView.as_view(), name="relic"),
]

src/grotto/api/views.py
from django.contrib import messages
from django.db.models import Prefetch, Count, Q
from django.shortcuts import get_object_or_404
from drf_yasg.utils import swagger_auto_schema
from rest_framework import generics, viewsets
from rest_framework.decorators import action
from rest_framework.response import Response

from grotto import celery_app
from foundry.api.serializers import ItemSerializer
from foundry.models import Item
from foundry.enum import ItemType
from foundry.services import ItemService
from grotto.api import serializers
from grotto.game.services import GameService
from grotto.services import GrottoGameWarning
from guild.api.serializers import CharacterSerializer, NonPlayerCharacterSerializer
from guild.models import Character, NonPlayerCharacter
from guild.services import PlayerCharacterService
from maze.api.serializers import RoomSerializer
from maze.models import Room, RoomExit


class TableauSerializerMixin:
    def get_tableau_serializer(self, *, character="from-request", room_pk="from-character"):
        if character == "from-request":
            character = self.request.character
        if character is not None:
            character.refresh_from_db()
        if room_pk == "from-character":
            room_pk = None
            if character is not None and character.room is not None:
                room_pk = character.room.pk
        stored_messages = []
        room = None
        if character is not None:
            try:
                # Use the manager to get the object so that it has full annotations
                room = (
                    Room.objects.filter(pk=room_pk)
                    .select_related("cenotaph")
                    .prefetch_related(
                        Prefetch(
                            "items",
                            queryset=Item.objects.exclude(
                                abstract_item__item_type=ItemType.TRAP,
                                active__isnull=False,
                            ),
                        )
                    )
                    .prefetch_related("occupants")
                    .prefetch_related("npcs")
                    .prefetch_related(
                        Prefetch(
                            "exits_from",
                            queryset=RoomExit.objects.all().annotate(
                                visit_count=Count(
                                    "to_room___visits",
                                    filter=Q(to_room___visits__character=character),
                                ),
                            )
                        )
                    )[0]
                )
            except (IndexError, AttributeError):
                pass
            messages_qs = character.messages.filter(seen=False)
            stored_messages = [
                {"message": m} for m in messages_qs.values_list("text", flat=True)
            ]
            messages_qs.update(seen=True)
        elif room_pk is not None:
            try:
                # Use the manager to get the object so that it has full annotations
                room = (
                    Room.objects.filter(pk=room_pk)
                    .select_related("cenotaph")
                    .prefetch_related(
                        Prefetch(
                            "items",
                            queryset=Item.objects.exclude(
                                abstract_item__item_type=ItemType.TRAP,
                            ),
                        )
                    )
                    .prefetch_related("occupants")
                    .prefetch_related("npcs")
                    .prefetch_related(
                        Prefetch(
                            "exits_from",
                        )
                    )[0]
                )
            except (IndexError, AttributeError):
                pass
        warnings = []
        if room is not None:
            warnings = room.warnings_for(character)
        return serializers.TableauSerializer(
            {
                "character": character,
                "room": room,
                "warnings": warnings,
                "messages": stored_messages
                + [{"message": str(m)} for m in messages.get_messages(self.request)],
            }
        )


class TableauAPIView(generics.GenericAPIView, TableauSerializerMixin):
    serializer_class = serializers.TableauSerializer

    def get(self, request, *args, **kwargs):
        serializer = self.get_tableau_serializer()
        # serializer.is_valid()
        return Response(serializer.data)


class GameActionMixin(TableauSerializerMixin):
    """
    Always use this as the first parent class for any game action view or viewset.
    It handles:
      * breaking the sour news to a player that their character is dead,
      * standardizing the response json to a game action
      * resolving actions (e.g. rolling for npc movement)
    """

    model = None
    service_class = None

    def dispatch(self, request, *args, **kwargs):
        self.dice_count = 0
        if request.character is None:
            raise GrottoGameWarning("Character does not exist")
        self.headers = self.default_response_headers
        # is this character alive
        if request.character.dead:
            # message about death
            messages.add_message(request, messages.INFO, request.character.deathnote)
            # Shortcut whatever action was requested because the player is dead!
            return self.finalize_response(request, None, *args, **kwargs)
        try:
            response = super().dispatch(request, *args, **kwargs)
        except GrottoGameWarning as e:
            self.dice_count = 0
            messages.add_message(request, messages.INFO, f"{e}")
            response = self.finalize_response(request, None, *args, **kwargs)
        return response

    def finalize_response(self, request, response, *args, **kwargs):
        self.advance_game()
        response = Response(self.get_tableau_serializer().data)
        return super().finalize_response(request, response, *args, **kwargs)

    def advance_game(self):
        if self.dice_count == 0:
            return
        game = GameService()
        # roll for dirtying room
        game.roll_to_dirty_room(
            room=self.request.character.room, dice_count=self.dice_count
        )
        game.roll_to_character_poop(
            character=self.request.character, dice_count=self.dice_count
        )
        # roll for NPC movements
        if self.request.character.room is not None:
            celery_app.send_task(
                "move_npcs",
                kwargs={
                    "dice_count": self.dice_count,
                    "level": self.request.character.room.level,
                    "character_pk": self.request.character.pk,
                },
            )

    def generic_action(self, request, pk, action="test", holder="character"):
        other = get_object_or_404(self.model, id=pk)
        service = self.service_class()
        service_return = getattr(service, action)(
            character=request.character, other=other
        )
        for message in service_return.messages:
            messages.add_message(request, messages.INFO, message)
        return Response("this should get overwritten!")


class EnterAPIView(GameActionMixin, generics.GenericAPIView):
    serializer_class = serializers.NullSerializer

    @swagger_auto_schema(responses={200: serializers.TableauSerializer})
    def post(self, request, *args, **kwargs):
        PlayerCharacterService().enter(character=request.character)


class RoomViewSet(GameActionMixin, viewsets.GenericViewSet):
    serializer_class = RoomSerializer
    queryset = Room.objects.all()

    @swagger_auto_schema(responses={200: serializers.TableauSerializer})
    @action(
        detail=True,
        methods=["post"],
        serializer_class=serializers.NullSerializer,
    )
    def move(self, request, pk):
        service_return = PlayerCharacterService().move(
            character=request.character, id=pk
        )
        for message in service_return.messages:
            messages.add_message(request, messages.INFO, message)
        self.dice_count += 1

    @swagger_auto_schema(responses={200: serializers.TableauSerializer})
    @action(
        detail=True,
        methods=["post"],
        serializer_class=serializers.NullSerializer,
    )
    def fire_arrow(self, request, pk):
        service_return = PlayerCharacterService().fire_arrow(
            character=request.character, id=pk
        )
        for message in service_return.messages:
            messages.add_message(request, messages.INFO, message)
        self.dice_count += 5

    @swagger_auto_schema(responses={200: serializers.TableauSerializer})
    @action(
        detail=True,
        methods=["post"],
        serializer_class=serializers.NullSerializer,
    )
    def place_trap(self, request, pk):
        service_return = PlayerCharacterService().place_trap(
            character=request.character, id=pk
        )
        for message in service_return.messages:
            messages.add_message(request, messages.INFO, message)
        self.dice_count += 5

    @swagger_auto_schema(responses={200: serializers.TableauSerializer})
    @action(
        detail=True,
        methods=["post"],
        serializer_class=serializers.NullSerializer,
    )
    def bash(self, request, pk):
        room = get_object_or_404(Room, id=pk)
        service_return = PlayerCharacterService().bash(
            character=request.character, other=room
        )
        for message in service_return.messages:
            messages.add_message(request, messages.INFO, message)
        self.dice_count += 5

    @swagger_auto_schema(responses={200: serializers.TableauSerializer})
    @action(
        detail=True,
        methods=["post"],
        serializer_class=serializers.NullSerializer,
    )

src/grotto/game/views.py
from django.conf import settings
from django.views.generic import TemplateView

from account.views import LoginRequiredMixin


class PlayView(LoginRequiredMixin, TemplateView):
    template_name = "play.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.request.user
        context.update(
            {
                "room_context": {
                    "user": {
                        "pk": user.pk,
                        "is_anonymous": user.is_anonymous,
                        "is_staff": user.is_staff,
                        "view_mode": str(user.preferences.view),
                    },
                    "base_url": settings.BASE_URL,
                }
            }
        )
        return context

src/grotto/views.py
class ActionMixin:
    """Puts action details on bottom of template"""

    actions = [
        {
            "url": "#",
            "text": "demo action 1",
        },
        {
            "url": "#",
            "text": "demo action 2",
        },
        {
            "url": "#",
            "text": "demo action 3",
        },
    ]

    def formatted_actions(self):
        """Hook for doing whatever mutation on actions that might be necessary"""
        return self.actions

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({"actions": self.formatted_actions()})
        return context

src/grotto/templates/static_pages/agreement.html
{% extends "base.html" %}

{% block page_title %}Code of Conduct{% endblock %}
{% block body_class %}agreement{% endblock %}
{% block main_section_class %}agreement{% endblock %}

{% block header %}<header></header>{% endblock %}

{% block content %}
updated 12/21/21
<p>
Grotto is a minimal platform for creating database-driven online game spaces. It's currently open-source and users are able create their own instances of the software. The creators of this software have applied an <a href="https://anticapitalist.software">anti-capitalist</a> software license that restricts use of this software not just to non-commercial use, but forbids uses that further the exploitation of labor towards profit.
</p>
<p>
Instances of Grotto may have norms and codes of conduct defined by the people who use them. This document that you are reading is a work in progress that defines a code of conduct for the specific instance of Grotto that is running on the wileywiggins.com domain. This instance of the Grotto software does not currently provide ways for players to interact with one another, but features are being added and changed as the underlying code is being developed for a site-specific artwork. Future versions of Grotto may contain names and life details about deceased people in the family of the software designer, as part of an artwork that utilizes the software. Future versions of the Grotto software may allow interactions that could be offensive, such as the symbolic dishonoring of deceased individuals. This is currently not a prohibited interaction. If you have questions about the specific nature of these sorts of symbolic actions, please don't hesitate to contact the email listed on the main grotto page. </p>
<p>
If features are added that allow player-to-player communication, you are expected to refrain from making unwelcome comments to other players in order to continue using the software. Some examples of these sorts of behaviors are:
<ul>
<li> Unwelcome comments regarding a person’s lifestyle choices and practices. </li>
<li> Threats, acts, or incitement of violence towards any individual, including encouraging a person to commit suicide or to engage in self-harm. </li>
<li> Posting or threatening to post other people’s personally identifying information ("doxing"). </li>
<li> Deliberate “outing” of any aspect of a person’s identity without their consent. </li>
<li> Deliberate misgendering or use of "dead” or rejected names. </li>
<li> Gratuitous or off-topic sexual images or behavior in spaces where they’re not appropriate. </li>

<li>Unwelcome sexual attention. Physical contact and simulated physical contact through text (e.g., descriptions like “*hug*” or “*backrub*”) without consent, or after a request for no contact or to stop. </li>
<li> Deliberate intimidation. </li>
<li> Patterns of inappropriate or unwanted social contact, such as requesting or assuming inappropriate levels of intimacy with others. Continued one-on-one communication after request to cease. Stalking or unwanted following, whether in-person or online. </li>
</ul>
<p>More details about reporting and consequences for these sorts of behaviors will be added as features that present a potential for player-to-payer harassment or abuse are added. 

</p>
{% endblock %}
<a href="/index.html">Back to main page</a>

src/grotto/templates/static_pages/index.html
{% extends "base.html" %}
{% load django_svelte %}
{% load static %}

{% block page_title %}Grotto{% endblock %}
{% block body_class %}index{% endblock %}

{% block header %}<header></header>{% endblock %}

{% block main_section_class %}welcome{% endblock %}

{% block content %}
  <img src="{% static 'images/title.png' %}"/ alt="Grotto">
  {% display_svelte "Attract.svelte" %}
  <div class="login"><a href="{% url 'game:play' %}">ENTER</a></div>

<div class="version">
  Running <a href="https://gitlab.com/grotto/grotto">Grotto {{ version }}</a>, created by Wiley Wiggins and Paul Stiverson</a>
</div>

{% endblock %}

src/grotto/templates/static_pages/reporting.html
{% extends "base.html" %}

{% block page_title %}Conduct Reporting{% endblock %}
{% block body_class %}reporting{% endblock %}
{% block main_section_class %}reporting{% endblock %}

{% block header %}<header></header>{% endblock %}

{% block content %}
  <p>This Grotto has not yet configured a reporting form. </p>
{% endblock %}

src/grotto/templates/static_pages/tmp.html
<html>
<head>
    <title>Just testing standalone animation display</title>
</head>
<body>
    <div id="animationdisplay-target"></div>
    <script id="animationdisplay-props" type="application/json">
    {
        "animationName": "attract",
        "animationRepeat": false,
        "animationFPS": 30,
        "flipbookUrl": "/static/grottopaint/maps/flipbooks.tmj",
        "spritesheetUrl": "/static/grottopaint/spritesheets/grotto40x30-cp437@1x.png"
    }
    </script>
    <script type="text/javascript" src="/static/AnimationDisplay.js"></script>
</body>