src/maze/api/urls.py
from rest_framework.routers import DefaultRouter

from maze.api import views

app_name = "maze-api"

router = DefaultRouter()
router.register("cenotaphs", views.CenotaphViewSet, basename="cenotaph")
router.register("visited", views.VisitedRoomViewSet, basename="visited")
router.register("rooms", views.RoomViewSet, basename="rooms")

urlpatterns = router.urls

src/maze/urls.py
from django.urls import path
from django.views.generic.base import TemplateView

from maze import views

app_name = "maze"
urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path(
        "character-map/",
        TemplateView.as_view(template_name="magicmap.html"),
        name="map",
    ),
    path("<slug:color_slug>/", views.RoomDetailView.as_view(), name="room"),
    path("cenotaph/<slug:color_slug>/", views.CenotaphView.as_view(), name="cenotaph"),
    path("graphics/<int:pk>/", views.RoomGraphicsView.as_view(), name="graphics"),
    path("cenotaph/<int:pk>/relic/", views.CenotaphRelicView.as_view(), name="relic"),
]

src/maze/api/views.py
from django.db.models import Count
from rest_framework import mixins, viewsets
from rest_framework.pagination import PageNumberPagination

from maze import models
from maze.api import serializers


class CenotaphViewSet(viewsets.GenericViewSet, mixins.RetrieveModelMixin):
    lookup_url_kwarg = "pk"
    serializer_class = serializers.CenotaphSerializer
    queryset = models.Cenotaph.objects.all()


class VisitedRoomViewSet(viewsets.GenericViewSet, mixins.ListModelMixin):
    """Shows the rooms that the _user_ has seen"""

    serializer_class = serializers.VisitedRoomSerializer
    queryset = models.Room.objects.visited()

    def get_queryset(self):
        if self.request.user.is_anonymous:
            return self.queryset
        return models.Room.objects.visited(user=self.request.user)


class RoomViewSet(
    viewsets.GenericViewSet, mixins.ListModelMixin, mixins.RetrieveModelMixin
):
    serializer_class = serializers.SimpleRoomSerializer
    queryset = models.Room.objects.filter(level__isnull=False).annotate(
        exit_count=Count("exits_from", distinct=True)
    )
    pagination_class = PageNumberPagination

src/maze/views.py
from random import choice

from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404
from django.shortcuts import redirect
from django.utils import timezone
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.conf import settings

from account.views import LoginRequiredMixin
from foundry.enum import ItemType
from maze.models import Cenotaph, Room
from maze.services import RoomService
from grotto.api.views import TableauSerializerMixin


class Index(ListView):
    template_name = "index.html"
    model = Room
    paginate_by = 25

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["now"] = timezone.now()
        return context

    def post(self, request):
        if request.user.is_staff:
            RoomService().generate()
        return redirect(".")  # points the user right back where they came from


class RoomDetailView(DetailView):
    model = Room
    template_name = "room.html"
    query_pk_and_slug = True
    slug_url_kwarg = "color_slug"
    slug_field = "color_slug"
    sanctity_adjectives = ("Cursed", "Mundane", "Sacred")
    cleanliness_adjectives = ("Profane", "Dirty", "Clean")
    actions = []

    def _room_level(self, item_type):
        room = self.object
        # check items in room
        _item = room.items.filter(
            abstract_item__item_type=item_type, active__isnull=False
        )

        active_item_count = sum([1 for candle in _item if candle.is_active])
        # active_item_count = 1
        if active_item_count > 0:
            return 2
        # check characters in room
        for character in room.occupants.all():
            # see if character has a candle
            _item = character.inventory.filter(
                abstract_item__item_type=item_type, active__isnull=False
            )
            active_item_count = sum([1 for candle in _item if candle.is_active])
            if active_item_count > 0:
                return 1
        return 0

    def get_room_level(self, descriptor="illumination"):
        room = self.object
        if descriptor == "cleanliness":
            return room.cleanliness
        if descriptor == "illumination":
            return self._room_level(ItemType.CANDLE)
        if descriptor == "sanctity":
            if room.is_cursed:
                return 0
            if self._room_level(ItemType.INCENSE) == 2:
                return 2
            return 1

    def get_room_adjective(self, descriptor):
        _level = self.get_room_level(descriptor)
        adjectives = getattr(self, f"{descriptor}_adjectives")
        try:
            return adjectives[_level]
        except IndexError:
            return "what?"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update(
            {
                "visits": self.object.visits,
                "illumination_level": self.get_room_level("illumination"),
                "sanctity_adjective": self.get_room_adjective("sanctity"),
                "cleanliness_adjective": self.get_room_adjective("cleanliness"),
            }
        )
        return context

    def get_object(self, queryset=None):
        """
        Return the object the view is displaying.
        Require `self.queryset` and a `pk` or `slug` argument in the URLconf.
        Subclasses can override this to return any object.
        """
        # Use a custom queryset if provided; this is required for subclasses
        # like DateDetailView
        if queryset is None:
            queryset = self.get_queryset()
        # Next, try looking up by primary key.
        pk = self.kwargs.get(self.pk_url_kwarg)
        slug = self.kwargs.get(self.slug_url_kwarg)
        if pk is not None:
            queryset = queryset.filter(pk=pk)
        # Next, try looking up by slug.
        if slug is not None and (pk is None or self.query_pk_and_slug):
            slug_field = self.get_slug_field()
            queryset = queryset.filter(**{slug_field: slug})
        # If none of those are defined, it's an error.
        if pk is None and slug is None:
            raise AttributeError(
                "Generic detail view %s must be called with either an object "
                "pk or a slug in the URLconf." % self.__class__.__name__
            )
        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            raise Http404(
                "No %(verbose_name)s found matching the query"
                % {"verbose_name": queryset.model._meta.verbose_name}
            )
        except self.model.MultipleObjectsReturned:
            for idx, _obj in enumerate(queryset):
                if idx == 0:
                    obj = _obj
                else:
                    _obj.color_slug += f"-{idx}"
                    _obj.save()
        return obj

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


class CenotaphView(DetailView):
    model = Room
    query_pk_and_slug = True
    slug_url_kwarg = "color_slug"
    slug_field = "color_slug"
    template_name = "cenotaph.html"

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        try:
            return obj.cenotaph
        except ObjectDoesNotExist:
            raise Http404("No cenotaph here")


class RoomGraphicsView(LoginRequiredMixin, TableauSerializerMixin, DetailView):
    template_name = "graphics.html"
    queryset = Room.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        instance = kwargs.pop("object")
        user = self.request.user
        context.update(
            {
                "graphics_context": {
                    "user": {
                        "pk": user.pk,
                        "is_anonymous": user.is_anonymous,
                        "is_staff": user.is_staff,
                    },
                    "base_url": settings.BASE_URL,
                    "raw_tableau": self.get_tableau_serializer(character=None, room_pk=instance.pk).data,
                }
            }
        )
        return context


class CenotaphRelicView(LoginRequiredMixin, DetailView):
    template_name = "item.html"
    queryset = Cenotaph.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        instance = self.get_object()
        relics = list(instance.relics.all())
        relic = None
        if relics:
            relic = choice(relics)
        context.update({
            "relic": relic
        })
        return context

src/maze/templates/cenotaph.html
{% extends "base.html" %}

{% load static %}
{% load humanize %}

{% block page_title %}{{object.name}}{% endblock %}

{% block body_class %}cenotaph{% endblock %}

{% block body_style %}background-color:{{object.room.color_hex}}{% endblock %}

{% block content %}
<section class="cenotaph-content">
  <h1>{{object.name}}</h1>
  {% if object.birth %}{{ object.birth }}{% else %}????{% endif%}&mdash;{% if object.death %}{{ object.death }}{% else %}????{% endif%}
  {% if object.portrait %}
    <img id="portrait" class="portrait" src="{{ object.portrait.url }}"/>
  {% endif %}

  <div class="obituary">
    <h3>Inscription:</h3>
    {{object.rendered_text|safe}}
  </div>
  <h3>Cenotaph Manifest:</h3>
  <ul class="events">
    {% for event in object.room.events.all reversed %}
      <li>{{ event.text }} &mdash; {{ event.created | naturaltime }}</li>
    {% endfor %}
  </ul>
  {{object.scene|safe}}
</section>
{% endblock %}

{% block footer %}
  <footer class="characterPanel">
    <div class="status-bar">
      You examine the Cenotaph
    </div>
    <div class="action-bar">
      <a href="{% url 'maze:room' object.room.color_slug %}">Return</a>
    </div>
  </footer>
{% endblock %}

src/maze/templates/graphics.html
{% extends "base.html" %}
{% load django_svelte %}

{% load static %}
{% load humanize %}

{% block page_title %}{{object.name}}{% endblock %}

{% block body_class %}graphical-view{% endblock %}

{% block inner_body %}
    {% display_svelte "Graphics.svelte" graphics_context %}
{% endblock %}

src/maze/templates/index.html
{% extends "base.html" %}

{% block body_class %}maze{% endblock %}

{% block content %}
  <section class="map-section">
    <h2>The map of <span class="yellow">Grotto</span> as we know it:</h2>
    <p>Spread out on the bed is a map and the tumped-out contents of a junk drawer.</p>

    <ul class="exits">
      {% for room in object_list %}
          <li><a href="{% url 'maze:room' room.color_slug %}">{{ room.name }}</a> -- <a href="{% url 'maze:graphics' room.pk %}">graphics</a> (created {{ room.pub_date|date }})</li>
      {% empty %}
          <li>No rooms yet.</li>
      {% endfor %}
    </ul>

    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
  </section>
{% endblock %}

src/maze/templates/magicmap.html
{% extends "base.html" %}
{% block head_script %}
    <script src="https://d3js.org/d3.v7.min.js"></script>
{% endblock %}
{% block head_meta %}
<meta
  http-equiv="Content-Security-Policy"
  content="default-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' https://d3js.org; style-src-elem 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com" />
{% endblock %}

{% block page_css %}
    {{ block.super }}
    <style>
        rect {
            stroke: #333;
            stroke-width: 1.5px;
            transition: stroke-width .5s ease-in-out;
        }
        rect:hover {
            stroke-width: 4px;
        }
    </style>
{% endblock %}

{% block inner_body %}
{% endblock %}


{% block page_script %}
    <script>
        const nodeSize = 16; // default node square
        function getNodeWidth(d) {
            return nodeSize + (d.exits ? d.exits.length : 0);
        }

        function getNodeHeight(d) {
            return nodeSize + (d.exits ? d.exits.length : 0);
        }


        // Fetching data
        Promise.all([
            fetch('/api/v1/game/tableau/').then(response => response.json()),
            fetch('/api/v1/guild/character_visits/').then(response => response.json())
        ]).then(([tableauData, visitedData]) => {

            const nodesMap = {
                [tableauData.room.pk]: {
                    ...tableauData.room,
                    visited: true,
                    warnings: tableauData.warnings  // Save warnings with the room
                }
            };
            visitedData.forEach(v => nodesMap[v.room.pk] = { ...v.room, visited: true });

            function getRoomsWithinSteps(nodesMap, startRoom, steps) {
                const visited = {};
                const stack = [{ node: startRoom, depth: 0 }];

                while (stack.length > 0) {
                    const { node, depth } = stack.pop();
                    if (!visited[node.pk]) {
                        visited[node.pk] = depth;
                        if (node.exits && depth < steps) {
                            node.exits.forEach(exit => {
                                if (nodesMap[exit.pk] && !visited[exit.pk]) {
                                    stack.push({ node: nodesMap[exit.pk], depth: depth + 1 });
                                }
                            });
                        }
                    }
                }
                return visited;
            }

            tableauData.room.exits.forEach(exit => {
                if (!nodesMap[exit.pk]) {
                    nodesMap[exit.pk] = {
                        ...exit,
                        unvisited: true,
                        visited: false
                    };
                }
            });

            const nodes = Object.values(nodesMap);
            const links = [];

            nodes.forEach(node => {
                if (node.exits) {
                    node.exits.forEach(exit => {
                        if (nodesMap[exit.pk]) {
                            links.push({
                                source: node.pk,
                                target: exit.pk,
                                unvisited: nodesMap[exit.pk].unvisited
                            });
                        }
                    });
                }
            });

            // Calculate rooms within 3 steps from the player's current room
            const closeRooms = getRoomsWithinSteps(nodesMap, tableauData.room, 3);

            // Filter nodes to include only rooms within 3 steps from the current room
            const filteredNodes = nodes.filter(node => closeRooms[node.pk] !== undefined);

            const filteredLinks = [];
            filteredNodes.forEach(node => {
                if (node.exits) {
                    node.exits.forEach(exit => {
                        if (nodesMap[exit.pk] && closeRooms[exit.pk] !== undefined) {
                            filteredLinks.push({
                                source: node.pk,
                                target: exit.pk,
                                unvisited: nodesMap[exit.pk].unvisited
                            });
                        }
                    });
                }
            });
            console.log("Filtered Nodes:", filteredNodes);
            console.log("Filtered Links:", filteredLinks);
            // SVG setup
            const width = 1200;
            const height = 600;

            const svg = d3.select("body").append("svg")
                .attr("width", width)
                .attr("height", height);

            // Force simulation setup
            const simulation = d3.forceSimulation(filteredNodes)
                .force("link", d3.forceLink(filteredLinks).id(d => d.pk).distance(80))
                .force("charge", d3.forceManyBody().strength(-700))
                .force("center", d3.forceCenter(width / 2, height / 2));

            // Draw links
            const link = svg.append("g")
                .selectAll("line")
                .data(filteredLinks)
                .enter().append("line")
                .attr("class", d => `link-${d.source.pk}-${d.target.pk}`)
                .attr("stroke", d => {
                    // Check if both source and target nodes are visited
                    if (d.source.visited && d.target.visited) {
                        return "#333";  // dark color for visited rooms
                    }
                    return "#ccc";  // Gray color for other cases
                })
                .style("stroke-dasharray", d => d.unvisited ? "5,5" : "none")  // Dashed line for unvisited exits
                .attr("stroke-opacity", 0.5);

            // Draw nodes

            const node = svg.append("g")
                .selectAll("rect")
                .data(filteredNodes)
                .enter().append("rect")
                .attr("width", d => getNodeWidth(d))
                .attr("height", d => getNodeHeight(d))
                .attr("fill", d => d.unvisited ? "#999" : d.color_hex)
                .style("shape-rendering" , "crispEdges")
                .style("stroke", d => {
                    if (d.warnings && d.warnings.length > 0) { // Check if the room has warnings
                        return "red"; // Red outline for rooms with warnings
                    }
                    return d.unvisited ? "#999" : "#333";
                })


            node.on("mouseover", function() {
                const d = d3.select(this).data()[0];
                // De-emphasize all links
                //console.log(d);
                link.style("stroke-opacity", 0.1);

                // Emphasize links connected to the hovered node
                link.filter(l => {
                    //console.log(typeof l.source.pk, typeof d.pk, l.source.pk, d.pk);
                    return l.source.pk == d.pk || l.target.pk == d.pk;
                })
                .style("stroke-opacity", 1);
            })
            .on("mouseout", function(d) {
                // Reset all link opacities back to original
                link.style("stroke-opacity", 0.5);
            });
            // Tooltip for nodes
            node.append("title")
                .text(d => {
                    let tooltipText = d.unvisited ? "unknown" : d.name;
                    if (d.warnings && d.warnings.length > 0) {
                        const warningMessages = d.warnings.map(w => w.warning).join("\n"); // Extract the warning texts
                        tooltipText += "\nWarnings: \n" + warningMessages;
                    }
                    return tooltipText;
                });
            const playerDot = svg.append("g")
                .selectAll("circle")
                .data(filteredNodes.filter(d => d.pk === tableauData.room.pk))
                .enter().append("circle")
                .attr("r", 4) // Size of the player dot
                .attr("fill", "black");

            // Update positions
            simulation.on("tick", () => {
                link
                    .attr("x1", d => d.source.x)
                    .attr("y1", d => d.source.y)
                    .attr("x2", d => d.target.x)
                    .attr("y2", d => d.target.y);

                node
                    .attr("x", d => d.x - getNodeWidth(d) / 2)
                    .attr("y", d => d.y - getNodeHeight(d) / 2);

                playerDot
                    .attr("cx", d => d.x)
                    .attr("cy", d => d.y);
            });

        });

    </script>
{% endblock %}

src/maze/templates/room.html
{% extends "base.html" %}

{% load humanize %}

{% block page_title %}{{object.name}}{% endblock %}

{% block body_class %}room {{ object.color_name }}{% endblock %}

{% block body_style %}background-color:{{object.color_hex}}{% endblock %}

{% block sidebar %}
  <sidebar>
    <h2>Exits:</h2>
    <ul class="exits">
      {% for exit in object.exits_from.all %}
        <li class="{{exit.direction.lower}}"><a href="{% url 'maze:room' exit.to_room.color_slug %}">{{exit.to_room.name}}</a></li>
      {% endfor %}
    </ul>
  </sidebar>
{% endblock %}

{% block content %}
  <section class="content">
    <h2>{{object.name}}</h2>
    <p>The room is {{ sanctity_adjective }} and {{ cleanliness_adjective }}. {% if illumination_level == 1 %}A player is holding a candle which dimly lights the room. A candle-holder on the wall is empty.{% elif illumination_level == 2%}A burning candle lights the room.{% else %}The room is totally dark.{% endif %}</p>
    <p class="description">{{ object.description }}</p>
    {% if object.cenotaph %}
    <p class="cenotaph"><a href="{% url 'maze:cenotaph' object.color_slug %}">View Cenotaph</a></p>
    {% endif %}
    {% comment %}
    log of events which occurred in this room
    {% endcomment %}
    <ul class="events">
      {% for event in object.events.all reversed %}
        <li>{{ event.text }} &mdash; {{ event.created | naturaltime }}</li>
      {% endfor %}
    </ul>
    <ul class="visits">
      {% for visit in visits %}
        {% if visit.character == character %}
          <li>You were here {{ visit.stamp_date | naturaltime }}</li>
        {% elif not visit.character %}
          <li>Something strange was here {{ visit.stamp_date | naturaltime }}</li>
        {% else %}
          <li>An unknown {{ visit.character.kind | lower }} was here {{ visit.stamp_date | naturaltime }}</li>
        {% endif %}
      {% endfor %}
    </ul>
  </section>
{% endblock %}